<?php

namespace ContainerBAgBQte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Edit' shared autowired service.
     *
     * @return \App\Form\Edit
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Edit.php';

        return $container->privates['App\\Form\\Edit'] = new \App\Form\Edit();
    }
}
