<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAgBQte\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAgBQte/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAgBQte.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAgBQte\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBAgBQte\App_KernelDevDebugContainer([
    'container.build_hash' => 'BAgBQte',
    'container.build_id' => '477dbcb8',
    'container.build_time' => 1682242571,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAgBQte');
